spring:
    datasource:
        url: jdbc:mysql://localhost:3306/student?createDatabaseIfNotExist=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
